version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "envs/**"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
